### ISSUE TITLE
Install Linux mint 18.1 Serena  Cinnamon Edititon log

### ISSUE THREAD

**Issue by JeremiahZhang** [JeremiahZhang/gopython#1]
# sys

   win7 + ubuntu 14.04LTS 双系统

# step 1 delete ubuntu

- 搜索教程, 如何删除 ubuntu系统：
  - 使用 [EasyBCD 2.3](https://neosmart.net/EasyBCD/)  ![EasyBCD](https://neosmart.net/EasyBCD/i/screenshots/Home.png) 在BCD development 下 write MBR 选择的是 vista+ 的那个 list 选项
  - 进入 我的电脑--> 管理 --> 磁盘 --> 删除 为ubuntu系统预留的卷, 变成空闲分区了，用来新建逻辑磁盘.
- 参考：[解决双系统下如何完全卸载Ubuntu系统 - 查看主题 • Ubuntu中文论坛](http://forum.ubuntu.org.cn/viewtopic.php?t=356575)

（网络上各种方法, 最后还是使用这种方法, 先前的双系统就是使用EasyBCD 制作引导的） 参见[jeremiahzhang.github.io/2015-10-27-Ubuntu-Install-DualBoot.md at master · JeremiahZhang/jeremiahzhang.github.io](https://github.com/JeremiahZhang/jeremiahzhang.github.io/blob/master/_posts/2015-10-27-Ubuntu-Install-DualBoot.md)

# step 2 U盘启动 安装 Mint

1. 从 [linux mint 官网](https://linuxmint.com/download.php) 下载 18.1 Cinnamon 版本 iso (32bit)
2. 验证  ISO images
3. 下载 [Rufus](https://rufus.akeo.ie/) 制作U盘启动
  - 坑1：使用 UUI 制作 iso 镜像启动（18.1）,  常识 3次，U盘启动是 boot 问题, 提示错误 No UI configuration, 解决未果, 去 mint 论坛 查询未果
 - 坑2： 使用 [LiLi](https://www.linuxliveusb.com/) 制作, 没有对应版本18.1的 使用17.2的安装信息, 还是不行, 什么错误忘记了, 缺少一个文件
 - 坑3： 最后使用 Rufus 2.13 按下图制作 选择的iso镜像 recommended ![Rufus 2.13](https://rufus.akeo.ie/pics/rufus_en.png) 还是未果, boot 不了
 - 填坑： 后来使用 Rufus 2.13 中的 DD镜像, 制作U盘启动盘, boot 成功, 安装Linux mint 18.1 在64g的SSD上, 覆盖原来系统, 现在就只剩下 linux mint 系统
    - Mint 安装比较简单而傻瓜 基本一键完成的 期间就是设置 加密 密码 和 登录密码
    - Mint 不像 Ubuntu那样是由商业公司发行的, mint 是社区发行的, 比较注重隐私, 好.

# 问题

> 制作U盘启动后的U盘本来8G的 现在剩下1.6G可以使用

在另一台 win10 电脑上解决

填坑：

1. 快速格式化 没有用 还是1.6g
2. 根据 [U盘做启动盘后，如何恢复原始容量](http://blog.sina.com.cn/s/blog_68f6e8a901014cvs.html)  + [How to Use DiskPart Commands in Windows 10?](http://www.disk-partition.com/windows-10/diskpart-windows-10-1203.html) 
  - ```cmd``` 键入 ```Diskpart``` 进入dispart 命令窗口
  - ```list disk```
  - ```select disk 1``` disk 1就是我那个 U 盘
  - ```clean``` 清楚空间内容
  - 到 电脑 ---》 磁盘管理 --》新建简单卷 释放空间 --》 u盘回到8g

# 后续

- [x] PC with mint 18.1 network set 网络连接配置
- [x] linux shell command 学习
- [x] git install ... 

# Mint

从此 成为薄荷一员 离开 windows 清爽. 
Mint 你值得拥有.

**Comment by JeremiahZhang** [comment]
# 网络连接配置

`Compaq Q35-105TX `

2017-04-10 中午回到宿舍, 有线连接电脑, 有网络信息, 但是浏览器firefox连接补上网络

`$ifconfig -a` 查看信息如下:

**Comment by JeremiahZhang** [comment]
# 电脑通过 Antroid 手机 上网

-[1] https://forums.linuxmint.com/viewtopic.php?t=241690#p1291366 

按着里面的方法 看了一下自己电脑的记录 一直出现的没有 eth0 和wlan0 信息 

继而想到就让电脑(无法连接网络)通过手机来连接网络
正好手头上有部 andriod 手机, 插上USB 进入调试模式, 尝试下 ifconfig 没有usb0的信息 肯定是没有连上, 继续search 得到 https://wiki.archlinux.org/index.php/android_tethering 教程, 原来还要打开andriod手机中的 USB网络共享, 这样不用设置 linux 电脑就可以直接上网的

之后按照第一个链接中的方法进行

`sudo apt-get update && sudo apt-get install linux-generic-hwe-16.04` 我不知道这是干嘛的 猜测是

- 系统更新 
- 下载 linux generic hwe linux 通用硬件扩展

`wget http://mirrors.kernel.org/ubuntu/pool/main/l/linux-firmware/linux-firmware_1.161.1_all.deb`

下载 firmware 固件 , 因为mint 是基于ubuntu扩展的, 所以上面命令中会出现ubuntu字样

`sudo dpkg -i linux-firmware_1.161.1_all.deb`

**Comment by JeremiahZhang** [comment]
# change hostname permanently in linux

[How to Set or Change System Hostname in Linux](http://www.tecmint.com/set-hostname-permanently-in-linux/)

`$sudo hostnamectl set-hostname mint`

then restart

**Comment by JeremiahZhang** [comment]
# sogou install 

[搜狗输入法 for linux 安装指南](http://pinyin.sogou.com/linux/help.php)

guess:

1.  install fcitx
2.  install sogou

**Comment by JeremiahZhang** [comment]
# sogou install 

[搜狗输入法 for linux 安装指南](http://pinyin.sogou.com/linux/help.php)

guess:

1.  install fcitx 
2.  install sogou 

do:

1. install 20 fcitx about package
2. install sogou

**Comment by JeremiahZhang** [comment]
# 主题配置

参考：[安装的第一个Linux系统 -Linux Mint 18.1 cinnamon](https://www.douban.com/note/598274695/)

$`sudo add-apt-repository ppa:numix/ppa`
$`sudo apt-get update`
$`sudo apt-get install numix-icon-theme-circle`

**Comment by JeremiahZhang** [comment]
# 主题配置

参考：[安装的第一个Linux系统 -Linux Mint 18.1 cinnamon](https://www.douban.com/note/598274695/)

$`sudo add-apt-repository ppa:numix/ppa`
$`sudo apt-get update`
$`sudo apt-get install numix-icon-theme-circle`

**Comment by JeremiahZhang** [comment]
# shadowsocks setting

参考: [Install And Use Shadowsocks Command Line Client on Linux - LinuxBabe.Com](https://www.linuxbabe.com/desktop-linux/how-to-install-and-use-shadowsocks-command-line-client)

do like in ubuntu 

`su`
`apt-get install pip`

error:

```
The following packages have unmet dependencies:
 python-pip : Depends: python-setuptools (>= 0.6c1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

so I went to [pip installing home page](https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py)

download `get-pip.py`， and in the dir did this:
`python get-pip.py`

there were some warning:

```
Exception:
Traceback (most recent call last):
  File "/tmp/tmprvEwEg/pip.zip/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/tmp/tmprvEwEg/pip.zip/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/tmp/tmprvEwEg/pip.zip/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/tmp/tmprvEwEg/pip.zip/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/tmp/tmprvEwEg/pip.zip/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/tmp/tmprvEwEg/pip.zip/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/tmp/tmprvEwEg/pip.zip/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/tmp/tmprvEwEg/pip.zip/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pip'
```

**Comment by JeremiahZhang** [comment]
# shadowsocks setting

参考: [Install And Use Shadowsocks Command Line Client on Linux - LinuxBabe.Com](https://www.linuxbabe.com/desktop-linux/how-to-install-and-use-shadowsocks-command-line-client)

do like in ubuntu 

`su`
`apt-get install pip`

error:

```
The following packages have unmet dependencies:
 python-pip : Depends: python-setuptools (>= 0.6c1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

so I went to [pip installing home page](https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py)

download `get-pip.py`， and in the dir did this:
`python get-pip.py`

there were some warning:

```
Exception:
Traceback (most recent call last):
  File "/tmp/tmprvEwEg/pip.zip/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/tmp/tmprvEwEg/pip.zip/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/tmp/tmprvEwEg/pip.zip/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/tmp/tmprvEwEg/pip.zip/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/tmp/tmprvEwEg/pip.zip/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/tmp/tmprvEwEg/pip.zip/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/tmp/tmprvEwEg/pip.zip/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/tmp/tmprvEwEg/pip.zip/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pip'
```

**Comment by JeremiahZhang** [comment]
# shadowsocks setting

参考: [Install And Use Shadowsocks Command Line Client on Linux - LinuxBabe.Com](https://www.linuxbabe.com/desktop-linux/how-to-install-and-use-shadowsocks-command-line-client)

do like in ubuntu 

`su`
`apt-get install pip`

error:

```
The following packages have unmet dependencies:
 python-pip : Depends: python-setuptools (>= 0.6c1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

so I went to [pip installing home page](https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py)

download `get-pip.py`， and in the dir did this:
`python get-pip.py`

there were some warning:

```
Exception:
Traceback (most recent call last):
  File "/tmp/tmprvEwEg/pip.zip/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/tmp/tmprvEwEg/pip.zip/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/tmp/tmprvEwEg/pip.zip/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/tmp/tmprvEwEg/pip.zip/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/tmp/tmprvEwEg/pip.zip/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/tmp/tmprvEwEg/pip.zip/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/tmp/tmprvEwEg/pip.zip/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/tmp/tmprvEwEg/pip.zip/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pip'
```

我想还是使用者 **Virtualenv**来解决吧. 
[Virtualenv — virtualenv 15.1.0 documentation](https://virtualenv.pypa.io/en/stable/)

**Comment by JeremiahZhang** [comment]
## 成功的ss设置

1. 下载shadowsocks ！ 

`sudo pip install shadowsocks`（这里我的电脑是客户端）

成功

2. 配置文件 `ss.json` root权限下保存在 /etc/ 中

{
    "server":"我买的vps中ss的ip地址",
    "server_port":xxx,
    "local_address":"127.0.0.1",
    "local_port":1080,
    "password":"我的密码",
    "timeout":300,
    "method":"aes-256-cfb",
    "fast_open":false
}

3. terminal 中执行 

`sslocal -c /etc/ss.json`

启动ss客户端

4. 浏览器配置（firefox）

- 下载 插件 AutoProxy-ng（直接使用firefox本身的[network配置是不行的](http://www.tomsguide.com/faq/id-1847788/configure-proxy-settings-mozilla-firefox.html)）, 重启浏览器。
- 配置端口（参考[ubuntu及linuxmint下实现浏览器与终端翻墙_琦行_新浪博客](http://blog.sina.com.cn/s/blog_8fcf8bf30102wlac.html)配置部分）

！[ref-image](http://img.blog.csdn.net/20160704134537600)

5. 设置好 就可以google

感觉好棒！ :+1: 

不过每次都要

`sslocal -c /etc/ss.json` 比较麻烦啊

参考[Ubuntu下shadowsocks配置说明_Linux教程_Linux公社-Linux系统门户网站](http://www.linuxidc.com/Linux/2015-09/123579.htm) 来写个脚本自动运行就ok啦

**Comment by JeremiahZhang** [comment]
# text editor

为了能编写markdown格式文件, 需要编辑器, 参考[10 Best Markdown Editors for Linux](http://www.tecmint.com/best-markdown-editors-for-linux/)

- vim [download : vim online](http://www.vim.org/download.php#unix) 反正都要用到, 就下载吧, 原来mint下没有 默认 vim
  - vim-markdown 支持插件 [suan/vim-instant-markdown: Instant Markdown previews from VIm!](https://github.com/suan/vim-instant-markdown)
- Emacs [GNU Emacs download - GNU Project](https://www.gnu.org/software/emacs/download.html#gnu-linux)

## vim install

using git

```
git clone https://github.com/vim/vim.git
cd vim/src
make
```

There are some errors:

```
no terminal library found
checking for tgetent()... configure: error: NOT FOUND!
      You need to install a terminal library; for example ncurses.
      Or specify the name of the library with --with-tlib.
Makefile:1829: recipe for target 'auto/config.mk' failed
make: *** [auto/config.mk] Error 1
```
