### ISSUE TITLE
Set up Python virtual environment in Linux Mint 18.1

### ISSUE THREAD

**Issue by JeremiahZhang** [JeremiahZhang/gopython#6]
## 启动

参考: [Pipenv & Virtual Environments — The Hitchhiker's Guide to Python](http://docs.python-guide.org/en/latest/dev/virtualenvs/)

安装 Pipenv.

## Install pipenv

```
anifacc@mint ~ $ pip3 -V
The program 'pip3' is currently not installed. You can install it by typing:
sudo apt install python3-pip
```

- 安装 pip

```
anifacc@mint ~ $ sudo apt install python3-pip
[sudo] password for anifacc: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  python-pip-whl
Recommended packages:
  build-essential python3-dev python3-setuptools python3-wheel
The following NEW packages will be installed:
  python-pip-whl python3-pip
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,219 kB of archives.
After this operation, 1,789 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://mirrors.aliyun.com/ubuntu xenial-updates/universe i386 python-pip-whl all 8.1.1-2ubuntu0.4 [1,110 kB]
Get:2 http://mirrors.aliyun.com/ubuntu xenial-updates/universe i386 python3-pip all 8.1.1-2ubuntu0.4 [109 kB]
Fetched 1,219 kB in 1s (883 kB/s)
Selecting previously unselected package python-pip-whl.
(Reading database ... 350790 files and directories currently installed.)
Preparing to unpack .../python-pip-whl_8.1.1-2ubuntu0.4_all.deb ...
Unpacking python-pip-whl (8.1.1-2ubuntu0.4) ...
Selecting previously unselected package python3-pip.
Preparing to unpack .../python3-pip_8.1.1-2ubuntu0.4_all.deb ...
Unpacking python3-pip (8.1.1-2ubuntu0.4) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up python-pip-whl (8.1.1-2ubuntu0.4) ...
Setting up python3-pip (8.1.1-2ubuntu0.4) ...
anifacc@mint ~ $ pip3 -V
pip 8.1.1 from /usr/lib/python3/dist-packages (python 3.5)
```

- install pipenv

使用 pip3 出现问题:

```
anifacc@mint ~ $ pip3 install --user pipenv
Collecting pipenv
  Downloading pipenv-8.2.6.tar.gz (3.7MB)
    100% |████████████████████████████████| 3.7MB 14kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-oetu478i/pipenv/
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

改用 pip , 成功

```
anifacc@mint ~ $ pip install --user pipenv
Collecting pipenv
  Using cached pipenv-8.2.6.tar.gz
Collecting virtualenv (from pipenv)
  Using cached virtualenv-15.1.0-py2.py3-none-any.whl
Collecting pew>=0.1.26 (from pipenv)
  Using cached pew-0.1.27-py2.py3-none-any.whl
Requirement already satisfied: pip>=9.0.1 in /usr/local/lib/python2.7/dist-packages (from pipenv)
Collecting requests>2.18.0 (from pipenv)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting flake8 (from pipenv)
  Using cached flake8-3.4.1-py2.py3-none-any.whl
Collecting urllib3>=1.21.1 (from pipenv)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 192kB/s 
Collecting pathlib; python_version == "2.7" (from pew>=0.1.26->pipenv)
  Downloading pathlib-1.0.1.tar.gz (49kB)
    100% |████████████████████████████████| 51kB 169kB/s 
Collecting shutilwhich; python_version == "2.7" (from pew>=0.1.26->pipenv)
  Downloading shutilwhich-1.1.0.tar.gz
Collecting backports.shutil-get-terminal-size; python_version == "2.7" (from pew>=0.1.26->pipenv)
  Downloading backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=17.1 in /usr/local/lib/python2.7/dist-packages (from pew>=0.1.26->pipenv)
Collecting virtualenv-clone>=0.2.5 (from pew>=0.1.26->pipenv)
  Downloading virtualenv-clone-0.2.6.tar.gz
Collecting certifi>=2017.4.17 (from requests>2.18.0->pipenv)
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
    100% |████████████████████████████████| 358kB 26kB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests>2.18.0->pipenv)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 51kB/s 
Collecting idna<2.7,>=2.5 (from requests>2.18.0->pipenv)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 61kB/s 
Requirement already satisfied: enum34; python_version < "3.4" in /usr/lib/python2.7/dist-packages (from flake8->pipenv)
Collecting configparser; python_version < "3.2" (from flake8->pipenv)
  Downloading configparser-3.5.0.tar.gz
Collecting mccabe<0.7.0,>=0.6.0 (from flake8->pipenv)
  Downloading mccabe-0.6.1-py2.py3-none-any.whl
Collecting pycodestyle<2.4.0,>=2.0.0 (from flake8->pipenv)
  Downloading pycodestyle-2.3.1-py2.py3-none-any.whl (45kB)
    100% |████████████████████████████████| 51kB 67kB/s 
Collecting pyflakes<1.6.0,>=1.5.0 (from flake8->pipenv)
  Downloading pyflakes-1.5.0-py2.py3-none-any.whl (225kB)
    100% |████████████████████████████████| 225kB 41kB/s 
Requirement already satisfied: six>=1.6.0 in /usr/lib/python2.7/dist-packages (from setuptools>=17.1->pew>=0.1.26->pipenv)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python2.7/dist-packages (from setuptools>=17.1->pew>=0.1.26->pipenv)
Requirement already satisfied: appdirs>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from setuptools>=17.1->pew>=0.1.26->pipenv)
Requirement already satisfied: pyparsing in /usr/local/lib/python2.7/dist-packages (from packaging>=16.8->setuptools>=17.1->pew>=0.1.26->pipenv)
Building wheels for collected packages: pipenv, pathlib, shutilwhich, virtualenv-clone, configparser
  Running setup.py bdist_wheel for pipenv ... done
  Stored in directory: /home/anifacc/.cache/pip/wheels/bb/27/52/280876ceda869276ad85958c1884a05902f1fc80fa82762758
  Running setup.py bdist_wheel for pathlib ... done
  Stored in directory: /home/anifacc/.cache/pip/wheels/2a/23/a5/d8803db5d631e9f391fe6defe982a238bf5483062eeb34e841
  Running setup.py bdist_wheel for shutilwhich ... done
  Stored in directory: /home/anifacc/.cache/pip/wheels/0e/28/70/d5cc6586f26d614b26901485f6f6072d35cbbb5bbeffb6ea43
  Running setup.py bdist_wheel for virtualenv-clone ... done
  Stored in directory: /home/anifacc/.cache/pip/wheels/24/51/ef/93120d304d240b4b6c2066454250a1626e04f73d34417b956d
  Running setup.py bdist_wheel for configparser ... done
  Stored in directory: /home/anifacc/.cache/pip/wheels/1c/bd/b4/277af3f6c40645661b4cd1c21df26aca0f2e1e9714a1d4cda8
Successfully built pipenv pathlib shutilwhich virtualenv-clone configparser
Installing collected packages: virtualenv, pathlib, shutilwhich, backports.shutil-get-terminal-size, virtualenv-clone, pew, certifi, chardet, idna, urllib3, requests, configparser, mccabe, pycodestyle, pyflakes, flake8, pipenv
Successfully installed backports.shutil-get-terminal-size-1.0.0 certifi-2017.7.27.1 chardet-3.0.4 configparser-3.5.0 flake8-3.4.1 idna-2.6 mccabe-0.6.1 pathlib-1.0.1 pew-0.1.27 pipenv-8.2.6 pycodestyle-2.3.1 pyflakes-1.5.0 requests-2.18.4 shutilwhich-1.1.0 urllib3-1.22 virtualenv-15.1.0 virtualenv-clone-0.2.6
```

不过问题来了, pip 使用的 python 2. 要是我想用安装 python 3 的库, 也能使用 该 pip 嘛?

## 使用 Pipenv

使用 参考: 

- [Basic Usage of Pipenv — pipenv 8.2.6 documentation](https://docs.pipenv.org/basics.html)
- [Pipenv: Python Dev Workflow for Humans — pipenv 8.2.6 documentation](https://docs.pipenv.org/)
```

**Comment by JeremiahZhang** [comment]
# 问题

- pip 和 pip3 的具体区别?

**Comment by JeremiahZhang** [comment]
# Pip3

```
anifacc@mint ~ $ python3 -m pip install --user pipenv
Collecting pipenv
  Using cached pipenv-8.2.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1bdmfp86/pipenv/
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

更新 pip3 

```
anifacc@mint ~ $ python3 -m pip install --upgrade pip
Collecting pip
  Using cached pip-9.0.1-py2.py3-none-any.whl
Installing collected packages: pip
Successfully installed pip-8.1.1
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
anifacc@mint ~ $ python3 -m pip install --upgrade pip
Requirement already up-to-date: pip in ./.local/lib/python3.5/site-packages
```

只能更新到8.1.1. (猜测 因为是 python3.5, 如果是 3.6 就可以)

之前的出现问题，　提示是

```
 Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named 'setuptools'
```

**Comment by JeremiahZhang** [comment]
# Now

- pip 安装 pipenv 完成
- pip3 安装 pipenv 完成

**Comment by JeremiahZhang** [comment]
# 使用 Pipenv 参考

- [pipenv 8.2.6 : Python Package Index](https://pypi.python.org/pypi/pipenv)

**Comment by JeremiahZhang** [comment]
# Usage

```
anifacc@mint /media/anifacc/geek/youtube_download $ pipenv --three install pafy
Creating a virtualenv for this project…
Using /usr/bin/python3 to create virtualenv…
⠋Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/anifacc/.local/share/virtualenvs/youtube_download-YJRREo8d/bin/python3
Also creating executable in /home/anifacc/.local/share/virtualenvs/youtube_download-YJRREo8d/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/anifacc/.local/share/virtualenvs/youtube_download-YJRREo8d
Creating a Pipfile for this project…
Installing pafy…
Collecting pafy
  Downloading pafy-0.5.3.1.tar.gz
Building wheels for collected packages: pafy
  Running setup.py bdist_wheel for pafy: started
  Running setup.py bdist_wheel for pafy: finished with status 'done'
  Stored in directory: /home/anifacc/.cache/pip/wheels/1d/81/dc/0cb0b1eea7b67d3d85e52764f8de1cebc0800e7c7bca8480c6
Successfully built pafy
Installing collected packages: pafy
Successfully installed pafy-0.5.3.1

Adding pafy to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (3a86d5)!
anifacc@mint /media/anifacc/geek/youtube_download $ ls
Pipfile  Pipfile.lock
```

**Comment by JeremiahZhang** [comment]
# Running your code

```
[dev-packages]anifacc@mint /media/anifacc/geek/youtube_download $ pipenv shell
Spawning environment shell (/bin/bash). Use 'exit' to leave.
source /home/anifacc/.local/share/virtualenvs/youtube_download-YJRREo8d/bin/activate
anifacc@mint /media/anifacc/geek/youtube_download $ source /home/anifacc/.local/share/virtualenvs/youtube_download-YJRREo8d/bin/activate
(youtube_download-YJRREo8d) anifacc@mint /media/anifacc/geek/youtube_download $ python
Python 3.5.2 (default, Aug 18 2017, 17:48:00) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

看 python virtual envs

```
anifacc@mint /media/anifacc/geek/youtube_download $ pipenv run which python
/home/anifacc/.local/share/virtualenvs/youtube_download-YJRREo8d/bin/python
```

可以 这样 跑程序:

```
pipenv run python my_project.py
```

简介些, 可以在 shell 脚本中 加入别名, 如

```
alias prp="pipenv run python"
```
