### ISSUE TITLE
Pipenv install numpy failed!

### ISSUE THREAD

**Issue by JeremiahZhang** [JeremiahZhang/gopython#7]
```
cd AI
```

我的 project,现在 AI 这个project 下面建立 virtual env 

```
Creating a virtualenv for this project…
Using /usr/bin/python3 to create virtualenv…
⠋Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/anifacc/.local/share/virtualenvs/AI-5UXR8Oos/bin/python3
Also creating executable in /home/anifacc/.local/share/virtualenvs/AI-5UXR8Oos/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/anifacc/.local/share/virtualenvs/AI-5UXR8Oos
Creating a Pipfile for this project…
anifacc@mint ~/Documents/gopython/AI $ ls
algorithm-basic                        data-mining-with-python        master-machine-learning-with-python  practice-machine-learning-with-python
book-neuron-network-and-deep-learning  deep-learning-with-python      ml-review-road.md                    protemplate.py
course-learning-from-data-of-caltech   machine-learning-book-of-zhou  Pipfile                              README.md
anifacc@mint ~/Documents/gopython/AI $ pipenv -h
Usage: pipenv [OPTIONS] COMMAND [ARGS]...

Options:
  --update         Update Pipenv & pip to latest.
  --where          Output project home information.
  --venv           Output virtualenv information.
  --py             Output Python interpreter information.
  --envs           Output Environment Variable options.
  --rm             Remove the virtualenv.
  --bare           Minimal output.
  --completion     Output completion (to be eval'd).
  --man            Display manpage.
  --three / --two  Use Python 3/2 when creating virtualenv.
  --python TEXT    Specify which version of Python virtualenv should use.
  --site-packages  Enable site-packages for the virtualenv.
  --jumbotron      An easter egg, effectively.
  --version        Show the version and exit.
  -h, --help       Show this message and exit.

Commands:
  check      Checks for security vulnerabilities and...
  graph      Displays currently–installed dependency graph...
  install    Installs provided packages and adds them to...
  lock       Generates Pipfile.lock.
  open       View a given module in your editor.
  run        Spawns a command installed into the...
  shell      Spawns a shell within the virtualenv.
  uninstall  Un-installs a provided package and removes it...
  update     Uninstalls all packages, and re-installs...
anifacc@mint ~/Documents/gopython/AI $ pipenv lock
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (711973)!
anifacc@mint ~/Documents/gopython/AI $ ls
algorithm-basic                        data-mining-with-python        master-machine-learning-with-python  Pipfile.lock                           README.md
book-neuron-network-and-deep-learning  deep-learning-with-python      ml-review-road.md                    practice-machine-learning-with-python
course-learning-from-data-of-caltech   machine-learning-book-of-zhou  Pipfile                              protemplate.py
anifacc@mint ~/Documents/gopython/AI $ pipenv install numpy --timeout 1000
Installing numpy…
Collecting numpy

Error:  An error occurred while installing numpy!
  Could not find a version that satisfies the requirement numpy (from versions: )
No matching distribution found for numpy

anifacc@mint ~/Documents/gopython/AI $ pip search numpy
Exception:
Traceback (most recent call last):
  File "/home/anifacc/.local/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 232, in _error_catcher
    yield
  File "/home/anifacc/.local/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 314, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 478, in readinto
    return self._readinto_chunked(b)
  File "/usr/lib/python3.5/http/client.py", line 578, in _readinto_chunked
    n = self._safe_readinto(mvb)
  File "/usr/lib/python3.5/http/client.py", line 623, in _safe_readinto
    n = self.fp.readinto(mvb)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anifacc/.local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/anifacc/.local/lib/python3.5/site-packages/pip/commands/search.py", line 45, in run
    pypi_hits = self.search(query, options)
  File "/home/anifacc/.local/lib/python3.5/site-packages/pip/commands/search.py", line 62, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1432, in __request
    verbose=self.__verbose
  File "/home/anifacc/.local/lib/python3.5/site-packages/pip/download.py", line 778, in request
    return self.parse_response(response.raw)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1311, in parse_response
    data = stream.read(1024)
  File "/home/anifacc/.local/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 324, in read
    flush_decoder = True
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/anifacc/.local/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 237, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.
anifacc@mint ~/Documents/gopython/AI $ cat ^C
anifacc@mint ~/Documents/gopython/AI $ cat Pipfile.lock 
{
    "_meta": {
        "hash": {
            "sha256": "101896288cdd87812255ae529b46012345afb654aafcb421f5a82afbbb711973"
        },
        "host-environment-markers": {
            "implementation_name": "cpython",
            "implementation_version": "3.5.2",
            "os_name": "posix",
            "platform_machine": "i686",
            "platform_python_implementation": "CPython",
            "platform_release": "4.10.0-35-generic",
            "platform_system": "Linux",
            "platform_version": "#39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:25 UTC 2017",
            "python_full_version": "3.5.2",
            "python_version": "3.5",
            "sys_platform": "linux"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.5"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {}
}
anifacc@mint ~/Documents/gopython/AI $ cat Pipfile
[[source]]
name = "pypi"
verify_ssl = true
url = "https://pypi.python.org/simple"

[requires]
python_version = "3.5"

[dev-packages]

[packages]
```

**Comment by JeremiahZhang** [comment]
不是 timeout 就是 

```
Error:  An error occurred while installing numpy!
  Could not find a version that satisfies the requirement numpy (from versions: )
No matching distribution found for numpy
````

暂时放弃, 选择 install anacoda

**Comment by JeremiahZhang** [comment]
# install anacoda

- download 根据系统及Python, 选择 Python2.7 linux 32bit版 [Downloads | Anaconda](https://www.anaconda.com/download/#linux)
- install 按照 [Installing on Linux | Anaconda: Documentation](https://docs.anaconda.com/anaconda/install/linux) 一步步执行, 完成
- 下一步 使用 参考 [Getting started | Anaconda: Documentation](https://docs.anaconda.com/anaconda/user-guide/getting-started.html)
  - 使用 GUI 参考: [Anaconda Navigator | Anaconda: Documentation](https://docs.anaconda.com/anaconda/navigator/)
  - 使用terminal 参考 [Overview — Conda documentation](https://conda.io/docs/user-guide/overview.html)
